### ISSUE TITLE
M2: sensitive information in cleartext cookie

### ISSUE THREAD

**Issue by kborer** [MetLifeLegalPlans/portunus#107]
### Report

![Screenshot from 2020-07-17 18-54-24](https://user-images.githubusercontent.com/640862/87836798-4ac38f80-c85f-11ea-9372-17ac194f7145.png)

![Screenshot from 2020-07-17 18-54-32](https://user-images.githubusercontent.com/640862/87836797-4a2af900-c85f-11ea-8c85-eafcf59049d7.png)

**Comment by Ian-MacLeod** [comment]
It wasn't clear to me from the statement of the issue, but after talking to Ambika it looks like the ask here is to have session cookies marked as temporary rather than persistent. We can do this using this setting: https://docs.djangoproject.com/en/3.1/ref/settings/#session-expire-at-browser-close. Should probably be done through zygoat.
