### ISSUE TITLE
Implement strong password policy

### ISSUE THREAD

**Issue by ambikads** [MetLifeLegalPlans/portunus#169]
Synopsys EH test finding.
Each of these can be separate PRs

1. Passwords must be at least eight (8) characters long. 
( We currently have it as 7 characters)

2. The application must compare the end user's selected password against a list of
commonly used, expected, or compromised passwords. This list may include but is not
limited to: dictionary words, commonly-used passwords, repetitive or sequential
characters, context-specific words (e.g., company name, application name, or username),
and passwords that have been compromised in a known data breach. The application
must reject the user's password if found to breached and provide a reason for rejection to
the user.
(I hope there is some library available we can make use of)

3. The application must generate at least six (6) characters long passwords when creating
temporary passwords such as first-time login passwords. The user must be required to
update their passwords next time they log in.
(This I am not sure if we need, doing the above two should help. We don't have many use cases for when we generate temporary password)

4. The application must enforce password change if there is evidence of compromise.

5. The application should provide a password strength meter to assist the user in choosing
a strong password.

![Screenshot from 2020-08-13 13-42-08](https://user-images.githubusercontent.com/11978599/90168452-19a98280-dd6b-11ea-98d8-60673144d585.png)

![Screenshot from 2020-08-13 13-43-16](https://user-images.githubusercontent.com/11978599/90168440-1615fb80-dd6b-11ea-85e3-3c3bc7293384.png)

**Comment by cviveiro** [comment]
It looks like we already check against the standard django package of common passwords. Do we have a specific common password that they checked against and we don't catch? @ambikads

**Comment by kborer** [comment]
If we already do it, then that part is done.

**Comment by cviveiro** [comment]
I think with #174 in we should have all of this done. 1) is enforced on the frontend so noone should be able to do it (we'll do the backend bit with pooja later: #198). 2) we already do, `testing1` brings up an error that it's too common. 3) we don't make one-time passwords, we just provide links with one-time tokens that expire. 5) we now have a strength bar, we don't need to use that score but we plan on using it later (#199). 

My only question is on 4) but also that kind of seems like it is on customer service rather than us, because we're not going to be automatically monitoring and resetting passwords anytime soon.

**Comment by ambikads** [comment]
Nice! I think its okay to close this after #174. I believe one of the common questions asked around password policy is if we have password expiration which I don't think is a good idea, these concerns should be alleviated when we have 2FA.
